# Periodic stats update

name: data update

# Controls when the workflow will run
on:
  # Triggers the workflow every hour
  schedule:
    - cron: '0 * * * *'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      - name: execute stat script
        run: |
          ./bin/run.sh
